server:
    port: 9090
    context-path: #/liuzh/


spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/jdbcstudy
        username: root
        password: restful
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        # 初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒 
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小 
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        
        
         
        
     # HTTP ENCODING
        http:
            encoding.charset: UTF-8
            encoding.enable: true
            encoding.force: true  
            
            
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        cache: false
        request-context-attribute: request


mybatis:
    typeAliasesPackage: com.ft.entity
    # dao层接口
    basePackage: com.ft.dao
    mapperLocations: classpath:mybatis/mapper/*.xml
    configLocation: classpath:mybatis/mybatis-config.xml
                
    
        
 # LOGGING
    logging:
        level:
            com.zsx.dao: DEBUG           
